package com.sylg.st.pojo;

public class ComApplication {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_application.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_application.team_name
     *
     * @mbggenerated
     */
    private String teamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_application.team_capacity
     *
     * @mbggenerated
     */
    private Integer teamCapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_application.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_application.member_name
     *
     * @mbggenerated
     */
    private String memberName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_application.member_school
     *
     * @mbggenerated
     */
    private String memberSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_application.team_biaoshi
     *
     * @mbggenerated
     */
    private String teamBiaoshi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_application.team_kouhao
     *
     * @mbggenerated
     */
    private String teamKouhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_application.com_type
     *
     * @mbggenerated
     */
    private String comType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_application.com_id
     *
     * @mbggenerated
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_application.captain
     *
     * @mbggenerated
     */
    private Integer captain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_application.member_qq
     *
     * @mbggenerated
     */
    private String memberQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_application.member_phone
     *
     * @mbggenerated
     */
    private String memberPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_application.mailbox
     *
     * @mbggenerated
     */
    private String mailbox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_application.teacher
     *
     * @mbggenerated
     */
    private String teacher;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_application.id
     *
     * @return the value of com_application.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_application.id
     *
     * @param id the value for com_application.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_application.team_name
     *
     * @return the value of com_application.team_name
     *
     * @mbggenerated
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_application.team_name
     *
     * @param teamName the value for com_application.team_name
     *
     * @mbggenerated
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_application.team_capacity
     *
     * @return the value of com_application.team_capacity
     *
     * @mbggenerated
     */
    public Integer getTeamCapacity() {
        return teamCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_application.team_capacity
     *
     * @param teamCapacity the value for com_application.team_capacity
     *
     * @mbggenerated
     */
    public void setTeamCapacity(Integer teamCapacity) {
        this.teamCapacity = teamCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_application.member_id
     *
     * @return the value of com_application.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_application.member_id
     *
     * @param memberId the value for com_application.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_application.member_name
     *
     * @return the value of com_application.member_name
     *
     * @mbggenerated
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_application.member_name
     *
     * @param memberName the value for com_application.member_name
     *
     * @mbggenerated
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_application.member_school
     *
     * @return the value of com_application.member_school
     *
     * @mbggenerated
     */
    public String getMemberSchool() {
        return memberSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_application.member_school
     *
     * @param memberSchool the value for com_application.member_school
     *
     * @mbggenerated
     */
    public void setMemberSchool(String memberSchool) {
        this.memberSchool = memberSchool == null ? null : memberSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_application.team_biaoshi
     *
     * @return the value of com_application.team_biaoshi
     *
     * @mbggenerated
     */
    public String getTeamBiaoshi() {
        return teamBiaoshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_application.team_biaoshi
     *
     * @param teamBiaoshi the value for com_application.team_biaoshi
     *
     * @mbggenerated
     */
    public void setTeamBiaoshi(String teamBiaoshi) {
        this.teamBiaoshi = teamBiaoshi == null ? null : teamBiaoshi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_application.team_kouhao
     *
     * @return the value of com_application.team_kouhao
     *
     * @mbggenerated
     */
    public String getTeamKouhao() {
        return teamKouhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_application.team_kouhao
     *
     * @param teamKouhao the value for com_application.team_kouhao
     *
     * @mbggenerated
     */
    public void setTeamKouhao(String teamKouhao) {
        this.teamKouhao = teamKouhao == null ? null : teamKouhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_application.com_type
     *
     * @return the value of com_application.com_type
     *
     * @mbggenerated
     */
    public String getComType() {
        return comType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_application.com_type
     *
     * @param comType the value for com_application.com_type
     *
     * @mbggenerated
     */
    public void setComType(String comType) {
        this.comType = comType == null ? null : comType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_application.com_id
     *
     * @return the value of com_application.com_id
     *
     * @mbggenerated
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_application.com_id
     *
     * @param comId the value for com_application.com_id
     *
     * @mbggenerated
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_application.captain
     *
     * @return the value of com_application.captain
     *
     * @mbggenerated
     */
    public Integer getCaptain() {
        return captain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_application.captain
     *
     * @param captain the value for com_application.captain
     *
     * @mbggenerated
     */
    public void setCaptain(Integer captain) {
        this.captain = captain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_application.member_qq
     *
     * @return the value of com_application.member_qq
     *
     * @mbggenerated
     */
    public String getMemberQq() {
        return memberQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_application.member_qq
     *
     * @param memberQq the value for com_application.member_qq
     *
     * @mbggenerated
     */
    public void setMemberQq(String memberQq) {
        this.memberQq = memberQq == null ? null : memberQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_application.member_phone
     *
     * @return the value of com_application.member_phone
     *
     * @mbggenerated
     */
    public String getMemberPhone() {
        return memberPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_application.member_phone
     *
     * @param memberPhone the value for com_application.member_phone
     *
     * @mbggenerated
     */
    public void setMemberPhone(String memberPhone) {
        this.memberPhone = memberPhone == null ? null : memberPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_application.mailbox
     *
     * @return the value of com_application.mailbox
     *
     * @mbggenerated
     */
    public String getMailbox() {
        return mailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_application.mailbox
     *
     * @param mailbox the value for com_application.mailbox
     *
     * @mbggenerated
     */
    public void setMailbox(String mailbox) {
        this.mailbox = mailbox == null ? null : mailbox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_application.teacher
     *
     * @return the value of com_application.teacher
     *
     * @mbggenerated
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_application.teacher
     *
     * @param teacher the value for com_application.teacher
     *
     * @mbggenerated
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }
}