package com.sylg.st.pojo;

public class Competation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competation.competation_id
     *
     * @mbggenerated
     */
    private Integer competationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competation.competation_name
     *
     * @mbggenerated
     */
    private String competationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competation.competation_time
     *
     * @mbggenerated
     */
    private String competationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competation.competation_fujian1
     *
     * @mbggenerated
     */
    private String competationFujian1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competation.startapply
     *
     * @mbggenerated
     */
    private Integer startapply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competation.fabu_time
     *
     * @mbggenerated
     */
    private String fabuTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competation.member_limit
     *
     * @mbggenerated
     */
    private Integer memberLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competation.jiezhibaoming
     *
     * @mbggenerated
     */
    private String jiezhibaoming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competation.competation_fujian2
     *
     * @mbggenerated
     */
    private String competationFujian2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competation.startbaoming
     *
     * @mbggenerated
     */
    private String startbaoming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competation.competation_explain
     *
     * @mbggenerated
     */
    private String competationExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competation.generalization
     *
     * @mbggenerated
     */
    private String generalization;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competation.competation_id
     *
     * @return the value of competation.competation_id
     *
     * @mbggenerated
     */
    public Integer getCompetationId() {
        return competationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competation.competation_id
     *
     * @param competationId the value for competation.competation_id
     *
     * @mbggenerated
     */
    public void setCompetationId(Integer competationId) {
        this.competationId = competationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competation.competation_name
     *
     * @return the value of competation.competation_name
     *
     * @mbggenerated
     */
    public String getCompetationName() {
        return competationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competation.competation_name
     *
     * @param competationName the value for competation.competation_name
     *
     * @mbggenerated
     */
    public void setCompetationName(String competationName) {
        this.competationName = competationName == null ? null : competationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competation.competation_time
     *
     * @return the value of competation.competation_time
     *
     * @mbggenerated
     */
    public String getCompetationTime() {
        return competationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competation.competation_time
     *
     * @param competationTime the value for competation.competation_time
     *
     * @mbggenerated
     */
    public void setCompetationTime(String competationTime) {
        this.competationTime = competationTime == null ? null : competationTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competation.competation_fujian1
     *
     * @return the value of competation.competation_fujian1
     *
     * @mbggenerated
     */
    public String getCompetationFujian1() {
        return competationFujian1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competation.competation_fujian1
     *
     * @param competationFujian1 the value for competation.competation_fujian1
     *
     * @mbggenerated
     */
    public void setCompetationFujian1(String competationFujian1) {
        this.competationFujian1 = competationFujian1 == null ? null : competationFujian1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competation.startapply
     *
     * @return the value of competation.startapply
     *
     * @mbggenerated
     */
    public Integer getStartapply() {
        return startapply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competation.startapply
     *
     * @param startapply the value for competation.startapply
     *
     * @mbggenerated
     */
    public void setStartapply(Integer startapply) {
        this.startapply = startapply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competation.fabu_time
     *
     * @return the value of competation.fabu_time
     *
     * @mbggenerated
     */
    public String getFabuTime() {
        return fabuTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competation.fabu_time
     *
     * @param fabuTime the value for competation.fabu_time
     *
     * @mbggenerated
     */
    public void setFabuTime(String fabuTime) {
        this.fabuTime = fabuTime == null ? null : fabuTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competation.member_limit
     *
     * @return the value of competation.member_limit
     *
     * @mbggenerated
     */
    public Integer getMemberLimit() {
        return memberLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competation.member_limit
     *
     * @param memberLimit the value for competation.member_limit
     *
     * @mbggenerated
     */
    public void setMemberLimit(Integer memberLimit) {
        this.memberLimit = memberLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competation.jiezhibaoming
     *
     * @return the value of competation.jiezhibaoming
     *
     * @mbggenerated
     */
    public String getJiezhibaoming() {
        return jiezhibaoming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competation.jiezhibaoming
     *
     * @param jiezhibaoming the value for competation.jiezhibaoming
     *
     * @mbggenerated
     */
    public void setJiezhibaoming(String jiezhibaoming) {
        this.jiezhibaoming = jiezhibaoming == null ? null : jiezhibaoming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competation.competation_fujian2
     *
     * @return the value of competation.competation_fujian2
     *
     * @mbggenerated
     */
    public String getCompetationFujian2() {
        return competationFujian2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competation.competation_fujian2
     *
     * @param competationFujian2 the value for competation.competation_fujian2
     *
     * @mbggenerated
     */
    public void setCompetationFujian2(String competationFujian2) {
        this.competationFujian2 = competationFujian2 == null ? null : competationFujian2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competation.startbaoming
     *
     * @return the value of competation.startbaoming
     *
     * @mbggenerated
     */
    public String getStartbaoming() {
        return startbaoming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competation.startbaoming
     *
     * @param startbaoming the value for competation.startbaoming
     *
     * @mbggenerated
     */
    public void setStartbaoming(String startbaoming) {
        this.startbaoming = startbaoming == null ? null : startbaoming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competation.competation_explain
     *
     * @return the value of competation.competation_explain
     *
     * @mbggenerated
     */
    public String getCompetationExplain() {
        return competationExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competation.competation_explain
     *
     * @param competationExplain the value for competation.competation_explain
     *
     * @mbggenerated
     */
    public void setCompetationExplain(String competationExplain) {
        this.competationExplain = competationExplain == null ? null : competationExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competation.generalization
     *
     * @return the value of competation.generalization
     *
     * @mbggenerated
     */
    public String getGeneralization() {
        return generalization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competation.generalization
     *
     * @param generalization the value for competation.generalization
     *
     * @mbggenerated
     */
    public void setGeneralization(String generalization) {
        this.generalization = generalization == null ? null : generalization.trim();
    }
}