package com.sylg.st.pojo;

import java.util.Date;

public class GoodsRecords {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsrecords.goodsrecords_id
     *
     * @mbggenerated
     */
    private Integer goodsrecordsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsrecords.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsrecords.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsrecords.goods_number
     *
     * @mbggenerated
     */
    private Integer goodsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsrecords.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsrecords.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsrecords.goodsrecords_id
     *
     * @return the value of goodsrecords.goodsrecords_id
     *
     * @mbggenerated
     */
    public Integer getGoodsrecordsId() {
        return goodsrecordsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsrecords.goodsrecords_id
     *
     * @param goodsrecordsId the value for goodsrecords.goodsrecords_id
     *
     * @mbggenerated
     */
    public void setGoodsrecordsId(Integer goodsrecordsId) {
        this.goodsrecordsId = goodsrecordsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsrecords.member_id
     *
     * @return the value of goodsrecords.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsrecords.member_id
     *
     * @param memberId the value for goodsrecords.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsrecords.goods_id
     *
     * @return the value of goodsrecords.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsrecords.goods_id
     *
     * @param goodsId the value for goodsrecords.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsrecords.goods_number
     *
     * @return the value of goodsrecords.goods_number
     *
     * @mbggenerated
     */
    public Integer getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsrecords.goods_number
     *
     * @param goodsNumber the value for goodsrecords.goods_number
     *
     * @mbggenerated
     */
    public void setGoodsNumber(Integer goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsrecords.state
     *
     * @return the value of goodsrecords.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsrecords.state
     *
     * @param state the value for goodsrecords.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsrecords.date
     *
     * @return the value of goodsrecords.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsrecords.date
     *
     * @param date the value for goodsrecords.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}