package com.sylg.st.pojo;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_count
     *
     * @mbggenerated
     */
    private Integer goodsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.is_xiaohao
     *
     * @mbggenerated
     */
    private Integer isXiaohao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_jpg_url
     *
     * @mbggenerated
     */
    private String goodsJpgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_location
     *
     * @mbggenerated
     */
    private String goodsLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_type
     *
     * @mbggenerated
     */
    private String goodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.size
     *
     * @mbggenerated
     */
    private String size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_id
     *
     * @return the value of goods.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_id
     *
     * @param goodsId the value for goods.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_name
     *
     * @return the value of goods.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_name
     *
     * @param goodsName the value for goods.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_count
     *
     * @return the value of goods.goods_count
     *
     * @mbggenerated
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_count
     *
     * @param goodsCount the value for goods.goods_count
     *
     * @mbggenerated
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.is_xiaohao
     *
     * @return the value of goods.is_xiaohao
     *
     * @mbggenerated
     */
    public Integer getIsXiaohao() {
        return isXiaohao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.is_xiaohao
     *
     * @param isXiaohao the value for goods.is_xiaohao
     *
     * @mbggenerated
     */
    public void setIsXiaohao(Integer isXiaohao) {
        this.isXiaohao = isXiaohao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_jpg_url
     *
     * @return the value of goods.goods_jpg_url
     *
     * @mbggenerated
     */
    public String getGoodsJpgUrl() {
        return goodsJpgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_jpg_url
     *
     * @param goodsJpgUrl the value for goods.goods_jpg_url
     *
     * @mbggenerated
     */
    public void setGoodsJpgUrl(String goodsJpgUrl) {
        this.goodsJpgUrl = goodsJpgUrl == null ? null : goodsJpgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_location
     *
     * @return the value of goods.goods_location
     *
     * @mbggenerated
     */
    public String getGoodsLocation() {
        return goodsLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_location
     *
     * @param goodsLocation the value for goods.goods_location
     *
     * @mbggenerated
     */
    public void setGoodsLocation(String goodsLocation) {
        this.goodsLocation = goodsLocation == null ? null : goodsLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_type
     *
     * @return the value of goods.goods_type
     *
     * @mbggenerated
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_type
     *
     * @param goodsType the value for goods.goods_type
     *
     * @mbggenerated
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType == null ? null : goodsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.size
     *
     * @return the value of goods.size
     *
     * @mbggenerated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.size
     *
     * @param size the value for goods.size
     *
     * @mbggenerated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }
}