package com.sylg.st.pojo;

public class Member {

    private Integer memberId;
    private String memberName;
    private String memberSex;
    private String schoolName;
    private String departmentName;
    private Integer memberQq;
    private String memberWechat;
    private String memberPhone;
    private String memberIdentify;
    private Integer memberTh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_id
     *
     * @return the value of member.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_id
     *
     * @param memberId the value for member.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_name
     *
     * @return the value of member.member_name
     *
     * @mbggenerated
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_name
     *
     * @param memberName the value for member.member_name
     *
     * @mbggenerated
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_sex
     *
     * @return the value of member.member_sex
     *
     * @mbggenerated
     */
    public String getMemberSex() {
        return memberSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_sex
     *
     * @param memberSex the value for member.member_sex
     *
     * @mbggenerated
     */
    public void setMemberSex(String memberSex) {
        this.memberSex = memberSex == null ? null : memberSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.school_name
     *
     * @return the value of member.school_name
     *
     * @mbggenerated
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.school_name
     *
     * @param schoolName the value for member.school_name
     *
     * @mbggenerated
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.department_name
     *
     * @return the value of member.department_name
     *
     * @mbggenerated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.department_name
     *
     * @param departmentName the value for member.department_name
     *
     * @mbggenerated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_qq
     *
     * @return the value of member.member_qq
     *
     * @mbggenerated
     */
    public Integer getMemberQq() {
        return memberQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_qq
     *
     * @param memberQq the value for member.member_qq
     *
     * @mbggenerated
     */
    public void setMemberQq(Integer memberQq) {
        this.memberQq = memberQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_wechat
     *
     * @return the value of member.member_wechat
     *
     * @mbggenerated
     */
    public String getMemberWechat() {
        return memberWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_wechat
     *
     * @param memberWechat the value for member.member_wechat
     *
     * @mbggenerated
     */
    public void setMemberWechat(String memberWechat) {
        this.memberWechat = memberWechat == null ? null : memberWechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_phone
     *
     * @return the value of member.member_phone
     *
     * @mbggenerated
     */
    public String getMemberPhone() {
        return memberPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_phone
     *
     * @param memberPhone the value for member.member_phone
     *
     * @mbggenerated
     */
    public void setMemberPhone(String memberPhone) {
        this.memberPhone = memberPhone == null ? null : memberPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_identify
     *
     * @return the value of member.member_identify
     *
     * @mbggenerated
     */
    public String getMemberIdentify() {
        return memberIdentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_identify
     *
     * @param memberIdentify the value for member.member_identify
     *
     * @mbggenerated
     */
    public void setMemberIdentify(String memberIdentify) {
        this.memberIdentify = memberIdentify == null ? null : memberIdentify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_th
     *
     * @return the value of member.member_th
     *
     * @mbggenerated
     */
    public Integer getMemberTh() {
        return memberTh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_th
     *
     * @param memberTh the value for member.member_th
     *
     * @mbggenerated
     */
    public void setMemberTh(Integer memberTh) {
        this.memberTh = memberTh;
    }
}