package com.sylg.st.pojo;

public class Membermac {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membermac.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membermac.mac
     *
     * @mbggenerated
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membermac.th
     *
     * @mbggenerated
     */
    private Integer th;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membermac.member_id
     *
     * @return the value of membermac.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membermac.member_id
     *
     * @param memberId the value for membermac.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membermac.mac
     *
     * @return the value of membermac.mac
     *
     * @mbggenerated
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membermac.mac
     *
     * @param mac the value for membermac.mac
     *
     * @mbggenerated
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membermac.th
     *
     * @return the value of membermac.th
     *
     * @mbggenerated
     */
    public Integer getTh() {
        return th;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membermac.th
     *
     * @param th the value for membermac.th
     *
     * @mbggenerated
     */
    public void setTh(Integer th) {
        this.th = th;
    }
}