package com.sylg.st.pojo;

public class Membertrainscore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membertrainscore.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membertrainscore.train_id
     *
     * @mbggenerated
     */
    private Integer trainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membertrainscore.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membertrainscore.score
     *
     * @mbggenerated
     */
    private Double score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membertrainscore.id
     *
     * @return the value of membertrainscore.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membertrainscore.id
     *
     * @param id the value for membertrainscore.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membertrainscore.train_id
     *
     * @return the value of membertrainscore.train_id
     *
     * @mbggenerated
     */
    public Integer getTrainId() {
        return trainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membertrainscore.train_id
     *
     * @param trainId the value for membertrainscore.train_id
     *
     * @mbggenerated
     */
    public void setTrainId(Integer trainId) {
        this.trainId = trainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membertrainscore.member_id
     *
     * @return the value of membertrainscore.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membertrainscore.member_id
     *
     * @param memberId the value for membertrainscore.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membertrainscore.score
     *
     * @return the value of membertrainscore.score
     *
     * @mbggenerated
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membertrainscore.score
     *
     * @param score the value for membertrainscore.score
     *
     * @mbggenerated
     */
    public void setScore(Double score) {
        this.score = score;
    }
}