package com.sylg.st.pojo;

import java.util.Date;

public class Moneyrecords {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moneyrecords.money_id
     *
     * @mbggenerated
     */
    private Integer moneyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moneyrecords.money_cost
     *
     * @mbggenerated
     */
    private Double moneyCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moneyrecords.money_left
     *
     * @mbggenerated
     */
    private Double moneyLeft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moneyrecords.money_date
     *
     * @mbggenerated
     */
    private Date moneyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moneyrecords.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moneyrecords.money_reason
     *
     * @mbggenerated
     */
    private String moneyReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moneyrecords.money_id
     *
     * @return the value of moneyrecords.money_id
     *
     * @mbggenerated
     */
    public Integer getMoneyId() {
        return moneyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moneyrecords.money_id
     *
     * @param moneyId the value for moneyrecords.money_id
     *
     * @mbggenerated
     */
    public void setMoneyId(Integer moneyId) {
        this.moneyId = moneyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moneyrecords.money_cost
     *
     * @return the value of moneyrecords.money_cost
     *
     * @mbggenerated
     */
    public Double getMoneyCost() {
        return moneyCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moneyrecords.money_cost
     *
     * @param moneyCost the value for moneyrecords.money_cost
     *
     * @mbggenerated
     */
    public void setMoneyCost(Double moneyCost) {
        this.moneyCost = moneyCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moneyrecords.money_left
     *
     * @return the value of moneyrecords.money_left
     *
     * @mbggenerated
     */
    public Double getMoneyLeft() {
        return moneyLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moneyrecords.money_left
     *
     * @param moneyLeft the value for moneyrecords.money_left
     *
     * @mbggenerated
     */
    public void setMoneyLeft(Double moneyLeft) {
        this.moneyLeft = moneyLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moneyrecords.money_date
     *
     * @return the value of moneyrecords.money_date
     *
     * @mbggenerated
     */
    public Date getMoneyDate() {
        return moneyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moneyrecords.money_date
     *
     * @param moneyDate the value for moneyrecords.money_date
     *
     * @mbggenerated
     */
    public void setMoneyDate(Date moneyDate) {
        this.moneyDate = moneyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moneyrecords.type
     *
     * @return the value of moneyrecords.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moneyrecords.type
     *
     * @param type the value for moneyrecords.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moneyrecords.money_reason
     *
     * @return the value of moneyrecords.money_reason
     *
     * @mbggenerated
     */
    public String getMoneyReason() {
        return moneyReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moneyrecords.money_reason
     *
     * @param moneyReason the value for moneyrecords.money_reason
     *
     * @mbggenerated
     */
    public void setMoneyReason(String moneyReason) {
        this.moneyReason = moneyReason == null ? null : moneyReason.trim();
    }
}