package com.sylg.st.pojo;

public class Nogiveback {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nogiveback.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nogiveback.goodrecord_id
     *
     * @mbggenerated
     */
    private Integer goodrecordId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nogiveback.id
     *
     * @return the value of nogiveback.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nogiveback.id
     *
     * @param id the value for nogiveback.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nogiveback.goodrecord_id
     *
     * @return the value of nogiveback.goodrecord_id
     *
     * @mbggenerated
     */
    public Integer getGoodrecordId() {
        return goodrecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nogiveback.goodrecord_id
     *
     * @param goodrecordId the value for nogiveback.goodrecord_id
     *
     * @mbggenerated
     */
    public void setGoodrecordId(Integer goodrecordId) {
        this.goodrecordId = goodrecordId;
    }
}