package com.sylg.st.pojo;

public class Pingfen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingfen.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingfen.member_name
     *
     * @mbggenerated
     */
    private String memberName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingfen.memberId
     *
     * @mbggenerated
     */
    private Integer memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingfen.th
     *
     * @mbggenerated
     */
    private Integer th;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingfen.score
     *
     * @mbggenerated
     */
    private Double score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingfen.id
     *
     * @return the value of pingfen.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingfen.id
     *
     * @param id the value for pingfen.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingfen.member_name
     *
     * @return the value of pingfen.member_name
     *
     * @mbggenerated
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingfen.member_name
     *
     * @param memberName the value for pingfen.member_name
     *
     * @mbggenerated
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingfen.memberId
     *
     * @return the value of pingfen.memberId
     *
     * @mbggenerated
     */
    public Integer getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingfen.memberId
     *
     * @param memberid the value for pingfen.memberId
     *
     * @mbggenerated
     */
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingfen.th
     *
     * @return the value of pingfen.th
     *
     * @mbggenerated
     */
    public Integer getTh() {
        return th;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingfen.th
     *
     * @param th the value for pingfen.th
     *
     * @mbggenerated
     */
    public void setTh(Integer th) {
        this.th = th;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingfen.score
     *
     * @return the value of pingfen.score
     *
     * @mbggenerated
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingfen.score
     *
     * @param score the value for pingfen.score
     *
     * @mbggenerated
     */
    public void setScore(Double score) {
        this.score = score;
    }
}