package com.sylg.st.pojo;

public class Playphone {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column playphone.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column playphone.com_id
     *
     * @mbggenerated
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column playphone.ximienum
     *
     * @mbggenerated
     */
    private Integer ximienum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column playphone.allnum
     *
     * @mbggenerated
     */
    private Integer allnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column playphone.id
     *
     * @return the value of playphone.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column playphone.id
     *
     * @param id the value for playphone.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column playphone.com_id
     *
     * @return the value of playphone.com_id
     *
     * @mbggenerated
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column playphone.com_id
     *
     * @param comId the value for playphone.com_id
     *
     * @mbggenerated
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column playphone.ximienum
     *
     * @return the value of playphone.ximienum
     *
     * @mbggenerated
     */
    public Integer getXimienum() {
        return ximienum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column playphone.ximienum
     *
     * @param ximienum the value for playphone.ximienum
     *
     * @mbggenerated
     */
    public void setXimienum(Integer ximienum) {
        this.ximienum = ximienum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column playphone.allnum
     *
     * @return the value of playphone.allnum
     *
     * @mbggenerated
     */
    public Integer getAllnum() {
        return allnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column playphone.allnum
     *
     * @param allnum the value for playphone.allnum
     *
     * @mbggenerated
     */
    public void setAllnum(Integer allnum) {
        this.allnum = allnum;
    }
}