package com.sylg.st.pojo;

public class Qiandaobiao {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiandaobiao.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiandaobiao.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiandaobiao.train_id
     *
     * @mbggenerated
     */
    private Integer trainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiandaobiao.attend
     *
     * @mbggenerated
     */
    private Integer attend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiandaobiao.id
     *
     * @return the value of qiandaobiao.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiandaobiao.id
     *
     * @param id the value for qiandaobiao.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiandaobiao.member_id
     *
     * @return the value of qiandaobiao.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiandaobiao.member_id
     *
     * @param memberId the value for qiandaobiao.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiandaobiao.train_id
     *
     * @return the value of qiandaobiao.train_id
     *
     * @mbggenerated
     */
    public Integer getTrainId() {
        return trainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiandaobiao.train_id
     *
     * @param trainId the value for qiandaobiao.train_id
     *
     * @mbggenerated
     */
    public void setTrainId(Integer trainId) {
        this.trainId = trainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiandaobiao.attend
     *
     * @return the value of qiandaobiao.attend
     *
     * @mbggenerated
     */
    public Integer getAttend() {
        return attend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiandaobiao.attend
     *
     * @param attend the value for qiandaobiao.attend
     *
     * @mbggenerated
     */
    public void setAttend(Integer attend) {
        this.attend = attend;
    }
}