package com.sylg.st.pojo;

public class Tongzhi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tongzhi.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tongzhi.tongzhi_name
     *
     * @mbggenerated
     */
    private String tongzhiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tongzhi.tongzhi_fabu
     *
     * @mbggenerated
     */
    private String tongzhiFabu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tongzhi.tongzhi_picture
     *
     * @mbggenerated
     */
    private String tongzhiPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tongzhi.tongzhi_context
     *
     * @mbggenerated
     */
    private String tongzhiContext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tongzhi.id
     *
     * @return the value of tongzhi.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tongzhi.id
     *
     * @param id the value for tongzhi.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tongzhi.tongzhi_name
     *
     * @return the value of tongzhi.tongzhi_name
     *
     * @mbggenerated
     */
    public String getTongzhiName() {
        return tongzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tongzhi.tongzhi_name
     *
     * @param tongzhiName the value for tongzhi.tongzhi_name
     *
     * @mbggenerated
     */
    public void setTongzhiName(String tongzhiName) {
        this.tongzhiName = tongzhiName == null ? null : tongzhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tongzhi.tongzhi_fabu
     *
     * @return the value of tongzhi.tongzhi_fabu
     *
     * @mbggenerated
     */
    public String getTongzhiFabu() {
        return tongzhiFabu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tongzhi.tongzhi_fabu
     *
     * @param tongzhiFabu the value for tongzhi.tongzhi_fabu
     *
     * @mbggenerated
     */
    public void setTongzhiFabu(String tongzhiFabu) {
        this.tongzhiFabu = tongzhiFabu == null ? null : tongzhiFabu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tongzhi.tongzhi_picture
     *
     * @return the value of tongzhi.tongzhi_picture
     *
     * @mbggenerated
     */
    public String getTongzhiPicture() {
        return tongzhiPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tongzhi.tongzhi_picture
     *
     * @param tongzhiPicture the value for tongzhi.tongzhi_picture
     *
     * @mbggenerated
     */
    public void setTongzhiPicture(String tongzhiPicture) {
        this.tongzhiPicture = tongzhiPicture == null ? null : tongzhiPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tongzhi.tongzhi_context
     *
     * @return the value of tongzhi.tongzhi_context
     *
     * @mbggenerated
     */
    public String getTongzhiContext() {
        return tongzhiContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tongzhi.tongzhi_context
     *
     * @param tongzhiContext the value for tongzhi.tongzhi_context
     *
     * @mbggenerated
     */
    public void setTongzhiContext(String tongzhiContext) {
        this.tongzhiContext = tongzhiContext == null ? null : tongzhiContext.trim();
    }
}