package com.sylg.st.pojo;

public class Train {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.train_id
     *
     * @mbggenerated
     */
    private Integer trainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.train_name
     *
     * @mbggenerated
     */
    private String trainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.train_time
     *
     * @mbggenerated
     */
    private String trainTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.train_room
     *
     * @mbggenerated
     */
    private String trainRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.fabu_time
     *
     * @mbggenerated
     */
    private String fabuTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.train_explain
     *
     * @mbggenerated
     */
    private String trainExplain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.train_id
     *
     * @return the value of train.train_id
     *
     * @mbggenerated
     */
    public Integer getTrainId() {
        return trainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.train_id
     *
     * @param trainId the value for train.train_id
     *
     * @mbggenerated
     */
    public void setTrainId(Integer trainId) {
        this.trainId = trainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.train_name
     *
     * @return the value of train.train_name
     *
     * @mbggenerated
     */
    public String getTrainName() {
        return trainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.train_name
     *
     * @param trainName the value for train.train_name
     *
     * @mbggenerated
     */
    public void setTrainName(String trainName) {
        this.trainName = trainName == null ? null : trainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.train_time
     *
     * @return the value of train.train_time
     *
     * @mbggenerated
     */
    public String getTrainTime() {
        return trainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.train_time
     *
     * @param trainTime the value for train.train_time
     *
     * @mbggenerated
     */
    public void setTrainTime(String trainTime) {
        this.trainTime = trainTime == null ? null : trainTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.train_room
     *
     * @return the value of train.train_room
     *
     * @mbggenerated
     */
    public String getTrainRoom() {
        return trainRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.train_room
     *
     * @param trainRoom the value for train.train_room
     *
     * @mbggenerated
     */
    public void setTrainRoom(String trainRoom) {
        this.trainRoom = trainRoom == null ? null : trainRoom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.fabu_time
     *
     * @return the value of train.fabu_time
     *
     * @mbggenerated
     */
    public String getFabuTime() {
        return fabuTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.fabu_time
     *
     * @param fabuTime the value for train.fabu_time
     *
     * @mbggenerated
     */
    public void setFabuTime(String fabuTime) {
        this.fabuTime = fabuTime == null ? null : fabuTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.train_explain
     *
     * @return the value of train.train_explain
     *
     * @mbggenerated
     */
    public String getTrainExplain() {
        return trainExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.train_explain
     *
     * @param trainExplain the value for train.train_explain
     *
     * @mbggenerated
     */
    public void setTrainExplain(String trainExplain) {
        this.trainExplain = trainExplain == null ? null : trainExplain.trim();
    }
}