package com.sylg.st.mapper;

import com.sylg.st.pojo.Adminpassword;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface AdminpasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpassword
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String adminName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpassword
     *
     * @mbggenerated
     */
    int insert(Adminpassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpassword
     *
     * @mbggenerated
     */
    Adminpassword selectByPrimaryKey(String adminName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpassword
     *
     * @mbggenerated
     */
    List<Adminpassword> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminpassword
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Adminpassword record);
}