package com.sylg.st.mapper;

import com.sylg.st.pojo.ComApplication;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface ComApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_application
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_application
     *
     * @mbggenerated
     */
    int insert(ComApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_application
     *
     * @mbggenerated
     */
    ComApplication selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_application
     *
     * @mbggenerated
     */
    List<ComApplication> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_application
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ComApplication record);
    ComApplication selectByMemberId(int memberId,int comId);
    List<ComApplication> selectByComId(int comId);
    List<ComApplication> selectByBiaoshi(String biaoshi);
    List<ComApplication> selectAllByMemberId(int memberId);
}