package com.sylg.st.mapper;

import com.sylg.st.pojo.Competation;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface CompetationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer competationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competation
     *
     * @mbggenerated
     */
    int insert(Competation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competation
     *
     * @mbggenerated
     */
    Competation selectByPrimaryKey(Integer competationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competation
     *
     * @mbggenerated
     */
    List<Competation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Competation record);
    int getLastestComID();
}