package com.sylg.st.mapper;

import com.sylg.st.pojo.Membermac;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface MembermacMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table membermac
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table membermac
     *
     * @mbggenerated
     */
    int insert(Membermac record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table membermac
     *
     * @mbggenerated
     */
    Membermac selectByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table membermac
     *
     * @mbggenerated
     */
    List<Membermac> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table membermac
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Membermac record);
    List<Membermac> selectByTh(Integer th);
    List<Integer> ths ();
    Membermac selectBymemberId(Integer memberId);
}