package com.sylg.st.mapper;

import com.sylg.st.pojo.Moneyrecords;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface MoneyrecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moneyrecords
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer moneyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moneyrecords
     *
     * @mbggenerated
     */
    int insert(Moneyrecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moneyrecords
     *
     * @mbggenerated
     */
    Moneyrecords selectByPrimaryKey(Integer moneyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moneyrecords
     *
     * @mbggenerated
     */
    List<Moneyrecords> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moneyrecords
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Moneyrecords record);
    double getMoney();
}