package com.sylg.st.mapper;

import com.sylg.st.pojo.Nogiveback;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface NogivebackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nogiveback
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);
    int deleteByGRIdKey(Integer goodrecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nogiveback
     *
     * @mbggenerated
     */
    int insert(Nogiveback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nogiveback
     *
     * @mbggenerated
     */
    Nogiveback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nogiveback
     *
     * @mbggenerated
     */
    List<Nogiveback> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nogiveback
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Nogiveback record);
    Nogiveback selectByGoodRecord(int goodRecord);
}