package com.sylg.st.mapper;

import com.sylg.st.pojo.Pingfen;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface PingfenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingfen
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingfen
     *
     * @mbggenerated
     */
    int insert(Pingfen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingfen
     *
     * @mbggenerated
     */
    Pingfen selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingfen
     *
     * @mbggenerated
     */
    List<Pingfen> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingfen
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Pingfen record);
    List<Pingfen> selectByTh(Integer th);
}