package com.sylg.st.mapper;

import com.sylg.st.pojo.Playphone;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface PlayphoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playphone
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playphone
     *
     * @mbggenerated
     */
    int insert(Playphone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playphone
     *
     * @mbggenerated
     */
    Playphone selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playphone
     *
     * @mbggenerated
     */
    List<Playphone> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playphone
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Playphone record);
    Playphone selectBytrainId(int comId);
    int deleteBytrainId(int comId);
}