package com.sylg.st.mapper;

import com.sylg.st.pojo.Tongzhi;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface TongzhiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tongzhi
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tongzhi
     *
     * @mbggenerated
     */
    int insert(Tongzhi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tongzhi
     *
     * @mbggenerated
     */
    Tongzhi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tongzhi
     *
     * @mbggenerated
     */
    List<Tongzhi> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tongzhi
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tongzhi record);
}