package com.sylg.st.mapper;

import com.sylg.st.pojo.Train;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface TrainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer trainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    int insert(Train record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    Train selectByPrimaryKey(Integer trainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    List<Train> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Train record);
    int getLatestTrainId();
}